services:
  api_service:
    build: ./api_service
    container_name: api_service
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./api_service:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project_db
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge